/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteuler.level001;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 *
 * Saskait;it visus Fiboniči skaitļus, kas ir pāra skaitļi, kas nav lielāki par 4 milnoniem
 * rezultāts: 4613732
 * 
 * @author Gatis
 */
public class Exc0002 {

  private static long total;

  public static void main(String[] args) {
    for (int i = 2; true; i++) {
      long fibTmp = fib(i);
      if (fibTmp <= 4000001) { // value < 4 mio (+1, because i=2)?
        if (fibTmp % 2 == 0) { // value even?
          total += fibTmp;
          System.out.println(fibTmp);
        } else {
          System.out.println(" (" + fibTmp + ")");
        }
      } else {
        break;
      }
    }
    System.out.println("\nSum of the even-valued terms: " + total);
  }

  private static long fib(int n) {
    if (n <= 1) {
      return n;
    } else {
      return fib(n - 1) + fib(n - 2);
    }
  }
}
